### ISSUE TITLE
Can't create local database

### ISSUE THREAD

**Issue by Serneum** [ElixirCLE/pairmotron#21]
```
crees  ~  workspace  elixir  pairmotron  mix ecto.create && mix ecto.migrate                                                                                                                    1   bug/missing-whitespace

12:50:02.945 [error] GenServer #PID<0.192.0> terminating
** (KeyError) key :username not found in: [types: true, backoff_type: :stop, pool: DBConnection.Connection, database: "template1", otp_app: :pairmotron, repo: Pairmotron.Repo, adapter: Ecto.Adapters.Postgres, hostname: "localhost", pool_size: 10]
    (elixir) lib/keyword.ex:333: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:414: Postgrex.Protocol.startup/2
    (postgrex) lib/postgrex/protocol.ex:353: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Pairmotron.Repo couldn't be created: an exception was raised:
    ** (KeyError) key :username not found in: [types: true, backoff_type: :stop, pool: DBConnection.Connection, database: "template1", otp_app: :pairmotron, repo: Pairmotron.Repo, adapter: Ecto.Adapters.Postgres, hostname: "localhost", pool_size: 10]
        (elixir) lib/keyword.ex:333: Keyword.fetch!/2
        (postgrex) lib/postgrex/protocol.ex:414: Postgrex.Protocol.startup/2
        (postgrex) lib/postgrex/protocol.ex:353: Postgrex.Protocol.handshake/2
        (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by ericworkman** [comment]
You need PG_USER=postgres or similar

**Comment by Serneum** [comment]
Why? I don't recall needing that with NermeSterts. Should we update the README?

**Comment by ericworkman** [comment]
We changed https://github.com/ElixirCLE/pairmotron/blob/master/config/dev.exs#L39

Please do update the readme

**Comment by ericworkman** [comment]
Track this with #22 please

**Comment by mbramson** [comment]
Created Issue #22 to address making this a bit more explained. Best way to get credentials working is to add PG_USER and PG_PASSWORD to your environment variables. If you don't want to do that for some reason, you can always just pave over that System.get_env with your plaintext credentials, just make sure that you don't push that up.
